export const html = (token: string) =>
  `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="dashboard-token" content="${token}"><title>Mission control</title><link rel="stylesheet" href="/style.css"><script src="/app.js" defer></script></head><body><header><h1>Mission control</h1><p>Local operator · evidence before action</p></header><p id="notice" role="status" aria-live="polite">Loading missions…</p><main><aside><h2>Runs</h2><div id="runs"></div><button id="refresh">Refresh runs</button></aside><article id="mission"><p>Select a mission.</p></article><section id="comparison"><h2>Run comparison</h2><label>Baseline <select id="baseline"></select></label><label>Candidate <select id="candidate"></select></label><button id="compare">Compare runs</button><div id="metrics"></div></section></main></body></html>`;
export const css = `:root{color-scheme:dark;font-family:system-ui,sans-serif;background:#0b1020;color:#edf3ff}*{box-sizing:border-box}body{margin:0;padding:24px;max-width:1500px;margin-inline:auto}header{border-bottom:1px solid #465375}h1{color:#70e5f4}h2{font-size:1.15rem;color:#c7adff}main{display:grid;grid-template-columns:250px minmax(0,1fr);gap:24px}section,aside{background:#131c31;padding:18px;border-radius:10px;margin-bottom:16px}article{min-width:0}#comparison{grid-column:1/-1}button,select{font:inherit;padding:10px;background:#243550;color:#fff;border:1px solid #71819f;border-radius:5px;margin:4px;max-width:100%}button{cursor:pointer}button:hover{background:#354c6b}button:disabled{opacity:.55;cursor:default}:focus-visible{outline:3px solid #70e5f4;outline-offset:3px}pre{white-space:pre-wrap;overflow-wrap:anywhere;background:#0b1020;padding:12px}p,summary{overflow-wrap:anywhere}details{border:1px solid #465375;padding:10px;margin-block:8px}summary{cursor:pointer}#notice{min-height:24px;color:#ffda92}#runs button{display:block;width:100%;text-align:left}table{border-collapse:collapse;width:100%}td,th{text-align:left;border-bottom:1px solid #465375;padding:10px;overflow-wrap:anywhere}.scroll{overflow:auto}.badge{color:#70e5f4;font-weight:bold}@media(max-width:700px){body{padding:12px}main{display:block}header h1{font-size:1.6rem}}`;
export const javascript = String.raw`
const $=id=>document.getElementById(id);let selected=null,timer=null,generation=0,mutating=false;
const token=document.querySelector('meta[name="dashboard-token"]').content;
function node(tag,text,parent){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;parent?.append(n);return n;}
function section(title,parent){const s=node('section',undefined,parent);node('h2',title,s);return s;}
function data(value,parent){node('pre',JSON.stringify(value,null,2),parent);}
function announce(text){$('notice').textContent=text;}
async function api(path,body){const response=await fetch(path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json','X-Dashboard-Token':token},body:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw new Error(result.error||'Request failed');return result;}
function details(title,value,parent){const d=node('details',undefined,parent);const summary=node('summary',title,d);summary.id='detail-'+title.replace(/[^a-zA-Z0-9]/g,'_');data(value,d);}
function schedule(view){clearTimeout(timer);if(view.dashboard?.resuming||view.dashboard?.reconciling||['RUNNING','WAITING_FOR_APPROVAL','UNCERTAIN_SIDE_EFFECT'].includes(view.status))timer=setTimeout(()=>inspect(false),1000);}
async function inspect(loading=true){if(!selected)return;const own=++generation,id=selected;if(loading)announce('Loading mission…');try{const view=await api('/api/runs/'+encodeURIComponent(id));if(own!==generation)return;render(view);schedule(view);void refreshStatuses();if(loading)announce('Mission loaded.');if(view.dashboard?.resumeError)announce('Resume failed: '+view.dashboard.resumeError);if(view.dashboard?.reconcileError)announce('Reconcile failed: '+view.dashboard.reconcileError);}catch(error){if(own===generation)announce(error.message);}}
async function mutate(suffix,payload){if(mutating)return;mutating=true;try{await api('/api/runs/'+encodeURIComponent(selected)+'/'+suffix,payload);announce(suffix==='approval'?'Decision recorded. Review the state, then use Resume.':suffix==='reconcile'?'Reconcile queued. Verification results appear below.':'Resume queued. Progress appears below.');await inspect(false);}catch(error){announce(error.message+'. Reloading current action; review it again before approving.');await inspect(false);}finally{mutating=false;await inspect(false);}}
function render(v){const expanded=new Set([...$('mission').querySelectorAll('details[open]')].map(d=>d.firstChild.textContent));const focus=document.activeElement?.id;const root=$('mission');root.replaceChildren();node('h2',v.mission.goal,root);node('p',v.mission.world+' · '+v.status,root).className='badge';if(v.mission.policy.sandbox)node('p','SIMULATION_ONLY — sandbox mission',root).className='badge';if(v.mission.world.startsWith('fixture'))node('p','FIXTURE MODE — synthetic evidence only',root).className='badge';
const events=[...v.events].sort((a,b)=>a.seq-b.seq);const last=kind=>events.filter(e=>e.kind===kind).at(-1);const action=v.pending?.action||last('plan.action')?.data.action;
const plan=section('Current plan and action',root);if(action){node('p',action.tool+' — '+action.reason,plan);node('p','Cited observations: '+action.evidenceRefs.join(', '),plan);details('Inspect exact tool input',action.input,plan);}else node('p',last('plan.finish')?.data.reason||'No action planned yet.',plan);
const policy=section('Policy and approval',root);data(v.mission.policy,policy);node('p','Writes started: '+new Set(events.filter(e=>e.kind==='tool.started'&&e.data.effect==='write').map(e=>e.data.step)).size+' / '+v.mission.policy.maxWrites,policy);data(last('policy.decision')?.data||'No policy decision yet',policy);
const request=events.filter(e=>e.kind==='approval.requested'&&e.data.digest===v.pending?.digest).at(-1);const expiry=request?Number(request.data.expiresAt):null;const expired=expiry!==null&&expiry<=Date.now();
if(v.pending){details('Exact pending action and digest',v.pending,policy);node('p',expiry===null?'Approval expiry: unavailable':'Approval expires: '+new Date(expiry).toISOString()+(expired?' — EXPIRED':''),policy);}
if(v.status==='WAITING_FOR_APPROVAL'){for(const [label,allow] of [['Approve exact action',true],['Deny action',false]]){const b=node('button',label,policy);b.id=allow?'approve':'deny';b.disabled=expired||mutating;b.onclick=()=>mutate('approval',{digest:v.pending.digest,allow});}if(expired)node('p','Request expired. Resume to refresh, then review the new request.',policy);}
if(!['CONFIRMED_SUCCESS','CONFIRMED_FAILURE','DENIED_BY_POLICY'].includes(v.status)){const b=node('button',v.status==='UNCERTAIN_SIDE_EFFECT'?'Resume verification':expired?'Refresh expired request':'Resume',policy);b.id='resume';b.disabled=!!v.dashboard?.resuming||mutating;b.onclick=()=>mutate('resume',{});}
if(v.status==='UNCERTAIN_SIDE_EFFECT')node('p','The write may have been accepted. Verification is pending; resume asks the runtime to reconcile the result.',policy);
if(v.status==='CONFIRMED_FAILURE'&&v.pending){const b=node('button','Reconcile the failed write',policy);b.id='reconcile';b.disabled=!!v.dashboard?.reconciling||mutating;b.onclick=()=>mutate('reconcile',{});node('p','The pending write was not confirmed in time. Reconcile re-runs only the verifier against the exact provider result; it never re-executes the action.',policy);}
if(v.status==='TOOL_UNAVAILABLE')node('p','Tool unavailable. Restore the connection before resuming.',policy);
const state=section('Current observed state',root);if(!v.observations.length)node('p','No observations yet.',state);for(const o of v.observations)details('#'+o.seq+' · '+o.tool+' · '+o.label,o.value,state);
const memory=section('Retrieved memory — historical context',root);data(last('memory.retrieved')?.data.entries||[],memory);
const evaluation=section('Independent evaluator',root);node('p',v.evaluation?(v.evaluation.passed?'Evaluator passed':'Evaluator failed')+' · score '+v.evaluation.score:'Not evaluated. Planner completion is not verified success.',evaluation);for(const c of v.evaluation?.checks||[])node('p',(c.passed?'PASS':'FAIL')+' · '+c.id+' · '+c.detail+' · evidence '+c.evidenceRefs.join(', '),evaluation);node('p','Confidence: Not measured',evaluation);const metrics=section('Model usage',root);if(v.modelMetrics?.modelCalls){node('p','Model calls: '+v.modelMetrics.modelCalls+' · Model request time: '+v.modelMetrics.modelLatencyMs+' ms',metrics);node('p','Input tokens: '+(v.modelMetrics.inputTokens??'Not reported')+' · Output tokens: '+(v.modelMetrics.outputTokens??'Not reported')+' · Model cost (USD): '+(v.modelMetrics.modelCostUsd??'Not reported'),metrics);}else node('p','No model generations recorded for this run.',metrics);for(const e of events.filter(e=>e.kind==='model.generation'))details('Generation #'+e.seq,e.data.generation,metrics);
const trace=section('Live trace',root);for(const e of events)details('#'+e.seq+' · '+e.kind+' · '+e.time,e.data,trace);for(const d of root.querySelectorAll('details'))d.open=expanded.has(d.firstChild.textContent);if(focus)document.getElementById(focus)?.focus();}
async function refreshStatuses(){try{const runs=await api('/api/runs');for(const button of $('runs').querySelectorAll('button')){const run=runs.find(run=>run.id===button.dataset.runId);if(run)button.textContent=run.id+' · '+run.status;}}catch{/* Inspection already reports connection errors. */}}
async function list(){try{const runs=await api('/api/runs');$('runs').replaceChildren();for(const name of ['baseline','candidate']){const old=$(name).value;$(name).replaceChildren();for(const r of runs){const o=node('option',r.id,$(name));o.value=r.id;}if(runs.some(r=>r.id===old))$(name).value=old;}for(const r of runs){const b=node('button',r.id+' · '+r.status,$('runs'));b.dataset.runId=r.id;b.onclick=()=>{clearTimeout(timer);selected=r.id;inspect();};}announce(runs.length?'Choose a mission.':'No runs yet. Create a mission in the runtime, then refresh.');if(!selected&&runs.length){selected=runs[0].id;await inspect();}}catch(error){announce(error.message);}}
$('refresh').onclick=list;$('compare').onclick=async()=>{try{const comparison=await api('/api/compare?baseline='+encodeURIComponent($('baseline').value)+'&candidate='+encodeURIComponent($('candidate').value));const target=$('metrics');target.replaceChildren();const wrap=node('div',undefined,target);wrap.className='scroll';const table=node('table',undefined,wrap);const row=node('tr',undefined,node('thead',undefined,table));node('th','Metric',row);for(const run of comparison.runs)node('th',run.label+' · '+run.runId,row);const body=node('tbody',undefined,table);for(const key of ['status','score','toolCalls','policyViolations','unverifiedWrites','modelCalls','modelLatencyMs','modelCostUsd','inputTokens','outputTokens']){const tr=node('tr',undefined,body);node('th',key,tr);for(const run of comparison.runs)node('td',run[key]===null||run[key]===undefined?'Not measured':String(run[key]),tr);}announce('Comparison loaded.');}catch(error){announce(error.message);}};
addEventListener('pagehide',()=>{clearTimeout(timer);generation++;});list();
`;
